/**
 * Created by ruslan on 18.05.17.
 */
import React, {Component} from 'react'
import {
    Button,
    Card,
    CardActionItem,
    CardActions,
    CardHorizontalBlock,
    CardMedia,
    CardMediaItem,
    CardPrimary,
    CardPrimarySubtitle,
    CardPrimaryTitle,
    CardSupportingText,
    Checkbox,
    CheckboxBackground,
    CheckboxCheckmark,
    CheckboxInput,
    CheckboxLabel,
    CheckboxMixedmark,
    CheckboxPath,
    Dialog,
    DialogBody,
    DialogFooter,
    DialogFooterButton,
    DialogHeader,
    DialogSurface,
    DialogTitle,
    DrawerListItemDetail,
    DrawerPermanent,
    DrawerPersistent,
    DrawerTemporary,
    Elevation,
    FAB,
    FABIcon,
    FormField,
    GridList,
    GridListTile,
    GridListTileContent,
    GridListTileIcon,
    GridListTilePrimary,
    GridListTileSecondary,
    GridListTileSupportText,
    GridListTileTitle,
    GridListTiles,
    Hint,
    HintElevation,
    HintInput,
    HintLabel,
    HintList,
    HintTags,
    HintTextfield,
    IconToggle,
    LayoutGrid,
    LayoutGridCell,
    List,
    ListDivider,
    ListGroup,
    ListGroupSubheader,
    ListItem,
    ListItemDetail,
    ListItemText,
    ListItemTextPrimary,
    ListItemTextSecondary,
    PermanentContent,
    PermanentList,
    PermanentListItem,
    PermanentToolbarSpacer,
    PersistentContent,
    PersistentDrawer,
    PersistentHeader,
    PersistentHeaderContent,
    PersistentListItem,
    PersistentToolbarSpacer,
    Radio,
    RadioInput,
    Ripple,
    Select,
    SelectItem,
    SelectItems,
    SelectMenu,
    SelectText,
    SimpleMenu,
    SimpleMenuAnchor,
    SimpleMenuItems,
    SimpleMenuListItem,
    Snackbar,
    SnackbarActionButton,
    SnackbarActionWrapper,
    SnackbarText,
    Switch,
    SwitchInput,
    SwitchLabel,
    TemporaryContent,
    TemporaryDrawer,
    TemporaryHeader,
    TemporaryHeaderContent,
    TemporaryListItem,
    TemporaryToolbarSpacer,
    Textfield,
    TextfieldHelptext,
    TextfieldInput,
    TextfieldLabel,
    Theme,
    Toolbar,
    ToolbarMain,
    ToolbarRow,
    ToolbarSection,
    ToolbarTitle,
    Typography,
    TypographyBody,
    TypographyCaption,
    TypographyDisplay,
    TypographyHeadline,
    TypographySubheading,
    TypographyTitle,
} from './lib'

export default class Drawer extends Component {
    render() {
        const {
            isOpenMenu,
            handleOpen,
            handleClose
        } = this.props;
        return (
            <DrawerTemporary
                open={isOpenMenu}
                onOpen={handleOpen}
                onClose={handleClose}
            >
                <TemporaryDrawer>
                    <TemporaryHeader>
                        <Theme
                            primaryBg
                            primaryPrimary
                        >
                        <TemporaryHeaderContent>Components</TemporaryHeaderContent>
                        </Theme>
                    </TemporaryHeader>
                    <TemporaryContent>
                        <TemporaryListItem>
                            <DrawerListItemDetail
                                start
                                icon
                            >
                                plus-circle
                            </DrawerListItemDetail>
                            Button
                        </TemporaryListItem>
                        <TemporaryListItem/>
                    </TemporaryContent>
                </TemporaryDrawer>
            </DrawerTemporary>
        )
    }
}